### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by gaagul** [gaagul/neeto-ui-challenge#8]

**Comment by gaagul** [comment]
Title of issue: Deploy application on Heroku

Deployed at https://neetoui-gaagul-production.herokuapp.com

Can be logged in using:
Username: oliver@example.com
Password: welcome

**Comment by yedhink** [comment]
@gaagul I've added some review comments for your closed PRs. Address and fix those comments and then please let me know over here.

**Comment by gaagul** [comment]
@yedhink I have made changes according to the reviews and merged it with the master branch.

**Comment by yedhink** [comment]
@gaagul I have added review comments: https://github.com/gaagul/neeto-ui-challenge/pull/20#discussion_r982114103

Once fixed point out over here.

**Comment by gaagul** [comment]
@yedhink I have made the suggested changes to the function, toCamelcase.

Below is a reference to how the function works.
![JavaScript Playground 2022-09-28 16-41-08](https://user-images.githubusercontent.com/70290286/192764913-4c2b7a23-c1c9-418e-afcf-9f1bcf7263c1.jpg)

**Comment by yedhink** [comment]
@gaagul LGTM. Go ahead and mark this task as completed and continue with the next task.
